apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-project-mlops
  labels:
    app: capstone-project-mlops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone-project-mlops
  template:
    metadata:
      labels:
        app: capstone-project-mlops
    spec:
      containers:
      - name: capstone-project-mlops
        # image: 020866158197.dkr.ecr.us-east-1.amazonaws.com/flask-app:latest
        image: 339713187643.dkr.ecr.us-east-1.amazonaws.com/capstone-project-mlops:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
        - name: CAPSTONE_TEST
          valueFrom:
            secretKeyRef:
              name: capstone-secret
              key: CAPSTONE_TEST

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-project-mlops-service
spec:
  type: LoadBalancer
  selector:
    app: capstone-project-mlops
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000